application: restextme
version: 1
runtime: python27
api_version: 1
threadsafe: false

libraries:
- name: jinja2
  version: latest


handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /ui
  static_dir: ui

- url: /s5/ui
  static_dir: ui

- url: /.*
  script: rstextme.py
